# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17d01f2153b285aefca48ce0a18f12366235f56a7997f671870f213599fb8c99db31656baa97ef94e272378118cb4025c59e929919f9dad266245e665d6136f5

test:
  secret_key_base: 5b01f0e2e4aa713c0294f782c437200640c17246df534b4b9836e664fac1fbcedf46c4c26edbdaa896448fb889ef83251a6c0a6b6dc9efb8d17c69132cce9ffb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
